{% set version = "5.2.0" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  - url: https://github.com/continuumIO/suitesparse-metis-for-windows/archive/master.zip   # [win]
    fn: suitesparse_cmake_setup.zip                                                        # [win]
  - url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ version }}.tar.gz
    sha256: 3c46c035ea8217649958a0f73360e825b0c9dcca4e32a9349d2c7678c0d48813
    patches:
      - 0001-only-build-UMFPACK-library.patch
    # nest folder on Windows so that it clobbers the older stuff from the cmake build that vendors it
    folder: SuiteSparse-to-move                                                            # [win]

build:
  number: 0
  features:
    - cuda                           # [ with_cuda ]
  run_exports:
    - {{ pin_subpackage("suitesparse") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
  host:
    - metis
    - mkl-devel  {{ mkl }}           # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - tbb-devel
    - cuda                           # [ with_cuda ]
  run:
    - cuda                           # [ with_cuda ]

test:
  commands:
    {% if unix %}
    - test -f ${PREFIX}/lib/libGPUQREngine${SHLIB_EXT}                # [with_cuda]
    - test -f ${PREFIX}/lib/libSuiteSparse_GPURuntime${SHLIB_EXT}     # [with_cuda]
    - test -f ${PREFIX}/lib/libamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libbtf${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libccolamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcholmod${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcolamd${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libcxsparse${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libklu${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libldl${SHLIB_EXT}
    - test -f ${PREFIX}/lib/librbio${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libspqr${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsuitesparseconfig${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libumfpack${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libGPUQREngine.a                          # [with_cuda]
    - test -f ${PREFIX}/lib/libSuiteSparse_GPURuntime.a               # [with_cuda]
    - test -f ${PREFIX}/lib/libamd.a
    - test -f ${PREFIX}/lib/libbtf.a
    - test -f ${PREFIX}/lib/libcamd.a
    - test -f ${PREFIX}/lib/libccolamd.a
    - test -f ${PREFIX}/lib/libcholmod.a
    - test -f ${PREFIX}/lib/libcolamd.a
    - test -f ${PREFIX}/lib/libcxsparse.a
    - test -f ${PREFIX}/lib/libgraphblas.a
    - test -f ${PREFIX}/lib/libklu.a
    - test -f ${PREFIX}/lib/libldl.a
    - test -f ${PREFIX}/lib/librbio.a
    - test -f ${PREFIX}/lib/libspqr.a
    - test -f ${PREFIX}/lib/libsuitesparseconfig.a
    - test -f ${PREFIX}/lib/libumfpack.a
    {% else %}
    - IF NOT EXIST %LIBRARY_LIB%\libGPUQREngine.lib exit 1            # [with_cuda]
    - IF NOT EXIST %LIBRARY_LIB%\libSuiteSparse_GPURuntime.lib exit 1 # [with_cuda]
    - IF NOT EXIST %LIBRARY_LIB%\libamd.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libbtf.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libcamd.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libccolamd.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libcholmod.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libcolamd.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libcxsparse.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libgraphblas.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libklu.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libldl.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libspqr.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\libumfpack.lib exit 1
    {% endif %}

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - v-turin
